### ISSUE TITLE
NoSuchMethodError: Node$DynamicTestExecutor.execute(org.junit.platform.engine.TestDescriptor, org.junit.platform.engine.EngineExecutionListener)

### ISSUE THREAD

**Issue by enricjaen** [spockframework/spock-example#87]
Hi, I am getting this error when I try to run spock tests.
```

[ERROR] uk.co.wowcher.vouchervalidityextension.voucherExtension.domain.model.aggregate.VoucherExtensionSpec.voucher extension should return the correct cost(Object,Object,Object,Object)  Time elapsed: 0.003 s  <<< ERROR!
java.lang.NoSuchMethodError: 'java.util.concurrent.Future org.junit.platform.engine.support.hierarchical.Node$DynamicTestExecutor.execute(org.junit.platform.engine.TestDescriptor, org.junit.platform.engine.EngineExecutionListener)'
	at org.spockframework.runtime.ParameterizedFeatureChildExecutor.execute(ParameterizedFeatureChildExecutor.java:104)
	at org.spockframework.runtime.PlatformParameterizedSpecRunner$1.runIteration(PlatformParameterizedSpecRunner.java:72)
	at org.spockframework.runtime.extension.IDataDriver.lambda$static$0(IDataDriver.java:37)
	at org.spockframework.runtime.PlatformParameterizedSpecRunner.runParameterizedFeature(PlatformParameterizedSpecRunner.java:47)
	at org.spockframework.runtime.ParameterizedFeatureNode.execute(ParameterizedFeatureNode.java:40)
	at org.spockframework.runtime.ParameterizedFeatureNode.execute(ParameterizedFeatureNode.java:16)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.spockframework.runtime.SpockNode.sneakyInvoke(SpockNode.java:40)
	at org.spockframework.runtime.FeatureNode.lambda$around$0(FeatureNode.java:41)
	at org.spockframework.runtime.PlatformSpecRunner.lambda$createMethodInfoForDoRunFeature$4(PlatformSpecRunner.java:199)
	at org.spockframework.runtime.model.MethodInfo.invoke(MethodInfo.java:156)
```

I am using the same configuration as in https://github.com/spockframework/spock-example/blob/master/pom.xml

I can see execute() is called with 2 params, but the execute() interface expects ony 1 param:

```
class ParameterizedFeatureChildExecutor {  // org.junit.platform:junit-platform-engine:jar:1.6.2

    public CompletableFuture<ExecutionResult> execute(TestDescriptor testDescriptor) {
       ...
       this.delegate.execute(testDescriptor, this.executionListener);
       ...
}



public interface Node<C extends EngineExecutionContext> { // org.spockframework:spock-core:jar:2.3-groovy-4.0

    public interface DynamicTestExecutor {
        void execute(TestDescriptor var1);
 }

```

The maven dependencies I have are:

```
[INFO] +- org.spockframework:spock-core:jar:2.3-groovy-4.0:test
[INFO] |  +- org.apache.groovy:groovy:jar:4.0.4:test
[INFO] |  \- org.junit.platform:junit-platform-engine:jar:1.6.2:test
[INFO] |     +- org.apiguardian:apiguardian-api:jar:1.1.0:test
[INFO] |     +- org.opentest4j:opentest4j:jar:1.2.0:test
[INFO] |     \- org.junit.platform:junit-platform-commons:jar:1.6.2:test
[INFO] +- org.spockframework:spock-spring:jar:2.3-groovy-4.0:test
[INFO] \- org.spockframework:spock-junit4:jar:2.3-groovy-4.0:test
[INFO]    \- junit:junit:jar:4.13:test
[INFO]       \- org.hamcrest:hamcrest-core:jar:2.2:test
```

Any ideas please?

**Comment by leonard84** [comment]
From the looks of it you need to update `org.junit.platform:junit-platform-engine:jar:1.6.2` , Spock 2.3 depends requires at least `1.9.0`.
